OPENROUTER_API_KEY: ''

SERPER_API_KEY: ''

FAL_KEY: ''

E2B_API_KEY: ''

ALLOWED_TOOLS_SYNERGY:
 - 
DISALLOWED_TOOLS_SYNERGY:
 - 

LOG_NAME: ''
LOG_DIR: ''
LOG_LEVEL: INFO
HTTP_SERVER_NAME: mirobody
HTTP_SERVER_VERSION: 1.0.1
HTTP_HOST: 0.0.0.0
HTTP_PORT: 18080
HTTP_URI_PREFIX: ''
HTTP_ROOT: mirobody/pub/htdoc
HTTP_HEADERS:
  Access-Control-Allow-Origin: '*'
  Access-Control-Allow-Credentials: 'true'
  Access-Control-Allow-Methods: '*'
  Access-Control-Allow-Headers: '*'
  Access-Control-Max-Age: '86400'
MCP_FRONTEND_URL: http://localhost:18080
MCP_PUBLIC_URL: http://localhost:18080
DATA_PUBLIC_URL: http://localhost:18080
QR_LOGIN_URL: ''
DATABASE_DECRYPTION_KEY: 'mydatabaseencryptionkey'
JWT_KEY: 'myjwtkey'

MINIO_ENDPOINT: 'http://minio:9000'
MINIO_PUBLIC_URL: 'http://localhost:9000'
MINIO_ACCESS_KEY: 'minioadmin'
MINIO_SECRET_KEY: 'minioapwd'
MINIO_BUCKET: 'theta'
MINIO_REGION: 'us-east-1'
MINIO_PUBLIC: 'true'

REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_DB: 0
REDIS_SSL: false
REDIS_SSL_CHECK_HOSTNAME: false
REDIS_SSL_CERT_REQS: none
REDIS_PASSWORD: 'your_secure_password_here' 
PG_HOST: db
PG_PORT: 5432
PG_USER: holistic_user
PG_DBNAME: holistic_db
PG_SCHEMA: theta_ai
PG_MIN_CONNECTION: 5
PG_MAX_CONNECTION: 20
PG_PASSWORD: 'holistic_password'
PG_ENCRYPTION_KEY: 'mydatabaseencryptionkey'

S3_KEY: ''
S3_TOKEN: ''
S3_REGION: ''
S3_BUCKET: ''
S3_PREFIX: ''
S3_CDN: ''
MCP_TOOL_DIRS:
- mirobody/pub/tools
- tools
MCP_RESOURCE_DIRS:
- mirobody/pub/resources
AGENT_DIRS:
- mirobody/pub/agents
JWT_PRIVATE_KEY: ''

GOOGLE_CLIENT_ID: ''
FIREBASE_PROJECT_ID: ''

APPLE_TEAM_ID: ''
APPLE_KEY_ID: ''
APPLE_PRIVATE_KEY: ''
APPLE_CLIENT_ID: ''
APPLE_AUTH_CLIENT_ID: ''

EMAIL_FROM: ''
EMAIL_FROM_NAME: ''
EMAIL_TEMPLATE: ''
EMAIL_SMTP_PASS: ''
EMAIL_PREDEFINE_CODES:
  demo@mirobody.ai: '777777'
ANTHROPIC_API_KEY: ''
OPENAI_API_KEY_RTC: ''
